version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-eslint/*"
          - angular-eslint
      primeng:
        patterns:
          - primeng
          - "@primeuix/*"
          - primeicons
          - tailwindcss-primeui
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
