import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = fileURLToPath(new URL("../", import.meta.url));
const fonts = [
  ["YekanBakh-Variable.woff2", "100 900"],
  ["YekanBakh-Regular.woff2", "400"],
  ["YekanBakh-Bold.woff2", "700"],
];

export async function prepareFonts(root = projectRoot) {
  const directory = resolve(root, "public/fonts/yekan-bakh");
  await mkdir(directory, { recursive: true });
  const faces = [];
  for (const [filename, weight] of fonts) {
    let data;
    try {
      data = await readFile(resolve(directory, filename));
    } catch (error) {
      if (error.code === "ENOENT") continue;
      throw error;
    }
    if (data.toString("ascii", 0, 4) !== "wOF2") {
      throw new Error(`${filename} must be a real WOFF2 file.`);
    }
    faces.push(`@font-face {
  font-family: "Yekan Bakh";
  src: url("/fonts/yekan-bakh/${filename}") format("woff2");
  font-weight: ${weight};
  font-style: normal;
  font-display: swap;
}`);
    if (filename === "YekanBakh-Variable.woff2") break;
  }
  const css = `/* Generated by scripts/prepare-fonts.mjs. See fonts/README.md. */\n${faces.length ? `${faces.join("\n")}\n` : ""}`;
  await mkdir(resolve(root, "src"), { recursive: true });
  await writeFile(resolve(root, "src/yekan-bakh-fonts.css"), css);
  return css;
}

if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  await prepareFonts();
}
